---
- name: creating a vpc
  hosts: '{{ hosts }}'
  remote_user: ec2-user
  become_method: sudo
  gather_facts: yes
  connection: ssh
  vars:
   hosts: local
  tasks:
    - name: creating vpc
      ec2_vpc:
        region: ap-northeast-1
        state: present
        cidr_block: 20.0.0.0/16
        resource_tags: { "Name":"Test" }
      register: vpc
